[tox]
isolated_build = true
skipsdist = true

[testenv]
deps =
    red-discordbot[test] @ git+https://github.com/Cog-Creators/Red-DiscordBot@{env:RED_DISCORDBOT_BRANCH:V3/develop}
    --requirement "{env:COG_REQUIREMENTS_TXT:requirements.txt}"
commands =
    # Exit code 5 is used by pytest to indicate "no tests collected" (which is not a failure for us).
    {env:SHELL:sh} -c 'pytest --config-file "{env:PYTEST_INI:pytest.ini}" "{env:COG_PATH}" {posargs} || test $? -eq 5'
