name: Cog Unit Tests

on:
  push:
    branches:
      - V3/develop
      - V3/testing
      - V3/prod
  pull_request:
    branches:
      - V3/develop
      - V3/testing
      - V3/prod
  workflow_dispatch:

env:
  COGS_PATH: "${{ github.workspace }}/cogs"

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      cogs: ${{ steps.build-cog-list.outputs.cogs }}
    steps:
      - uses: actions/checkout@v4

      - name: Build cog list
        id: build-cog-list
        run: |
          json=$(find "${COGS_PATH}" -mindepth 1 -maxdepth 1 -type "d" -printf "%f\n" | jq -R | jq -sc)
          echo "cogs=${json}" >> $GITHUB_OUTPUT

  test:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        cog: ${{ fromJson(needs.discover.outputs.cogs) }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract cog requirements
        run: |
          if [ -f "${COGS_PATH}/${{ matrix.cog }}/info.json" ]; then
            jq -r ".requirements[]? // empty" "${COGS_PATH}/${{ matrix.cog }}/info.json" > "${COGS_PATH}/${{ matrix.cog }}/.requirements.txt"
          else
            touch "${COGS_PATH}/${{ matrix.cog }}/.requirements.txt"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Extract Red version
        id: extract-red-version
        run: |
          version=$(python "${{ github.workspace }}/setup.py" --version 2> /dev/null)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Cache pip + tox
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .tox/${{ matrix.cog }}
          key: "${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.cog }}-${{ hashFiles(format('cogs/{0}/.requirements.txt', matrix.cog)) }}"
          restore-keys: "${{ runner.os }}-py${{ matrix.python-version }}-${{ matrix.cog }}-"

      - name: Install tox
        run: pip install "tox"

      - name: Run tox
        env:
          COG_PATH: "${{ env.COGS_PATH }}/${{ matrix.cog }}"
          COG_REQUIREMENTS_TXT: "${{ env.COGS_PATH }}/${{ matrix.cog }}/.requirements.txt"
          PYTEST_INI: "${{ github.workspace }}/.github/workflows/configs/cog_unit_test_pytest.ini"
          RED_DISCORDBOT_BRANCH: "${{ steps.extract-red-version.outputs.version }}"
        run: tox -c "${{ github.workspace }}/.github/workflows/configs/cog_unit_test_tox.ini"
