name: Cog Unit Tests
on:
  pull_request:
  push:

jobs:
  run-tests:
    name: Run cog unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python3
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-mock
      - name: Install Red-DiscordBot
        run: |
          pip install .
      - name: Run unit tests
        run: |
          pytest cogs/*/test* 
